spring.application.name=mindpanel-2.0

spring.data.mongodb.uri=mongodb://admin:adminnimda@localhost:27017/mindpanel?authSource=admin

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/mindpanel
